name: publish-actions
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'
      - name: Install and build
        run: |
          pnpm install
          pnpm run build --base=/angular-signals-how-do-they-work/
      - name: Deploy to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Benjamin Legrand" && git config user.email "b.legrand@groupeonepoint.com"
          npm run deploy -- --repo=https://b-legrand:${{ secrets.GITHUB_TOKEN }}@github.com/b-legrand/angular-signals-how-do-they-work.git --message="updates from ${GITHUB_SHA}" --no-history
